=== holamellamoyago/DAM-24-25-YOM/Asignaturas/Lenguaje de marcas/Trimestre 2/Unidad 3/Repaso/pilotos.dtd
<!ELEMENT formula1 (piloto+, escuderia+, pilotoGanador)>
<!ELEMENT piloto (nombre, numero)>

<!ENTITY  % neumaticos 
  "neumaticos (blandos | medios | duros) #REQUIRED ">

<!ATTLIST piloto codigo ID  #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT numero (#PCDATA)>

<!ELEMENT escuderia (nombre, piloto1, piloto2, coche*, kart*)>
<!ELEMENT piloto1 (#PCDATA)>
<!ELEMENT piloto2 (#PCDATA)>
<!ELEMENT coche (marcaMotor)>
<!ATTLIST coche neumaticos (blandos | medios | duros) "medios"> 
<!ELEMENT marcaMotor (#PCDATA)>

<!ELEMENT pilotoGanador (#PCDATA)>
<!ATTLIST pilotoGanador escuderia NMTOKENS #REQUIRED>
<!ATTLIST pilotoGanador ref IDREF  #IMPLIED>

<!ELEMENT kart (#PCDATA)>
<!ATTLIST kart %neumaticos;>

=== holamellamoyago/DAM-24-25-YOM/Asignaturas/Lenguaje de marcas/Trimestre 2/Unidad 3/Repaso/pilotos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE formula1 SYSTEM "pilotos.dtd">
<formula1>
  <piloto codigo="A">
      <nombre>Fernando Alonso</nombre>
      <numero>33</numero>
  </piloto>
  
  <escuderia>
     <nombre>Aston martin</nombre>
     <piloto1>Fernando</piloto1>
     <piloto2>Carlos</piloto2>
     
     <coche neumaticos="medios">
         <marcaMotor>Aston Martin </marcaMotor>
     </coche>
     
      <kart neumaticos="blandos">
        Kart
      </kart>
     
  </escuderia>
  
  
  
  <pilotoGanador escuderia="RedBull Racing" ref="A">Max Verstapen</pilotoGanador>
  
</formula1>
