=== holamellamoyago/DAM-24-25-YOM/Asignaturas/Lenguaje de marcas/Trimestre 2/Unidad 3/UD3_T8_yagootero.dtd
<!ELEMENT curriculumVitae (presentacion, (estudios | experienciaLaboral)+, (idiomas | deportes | otros)*, referencias*, observaciones?)> 
<!ELEMENT presentacion (#PCDATA)>
<!ELEMENT estudios (#PCDATA)>

<!ATTLIST estudios notaMedia CDATA #REQUIRED>

<!ELEMENT experienciaLaboral (nombre, horas)>
<!ELEMENT nombre  (#PCDATA)>
<!ELEMENT horas  (#PCDATA)>


<!ELEMENT idiomas EMPTY>
<!ATTLIST idiomas nombre CDATA #REQUIRED>
<!ATTLIST idiomas nivel (bajo | medio | alto) "medio">

<!ELEMENT deportes (#PCDATA)>
<!ELEMENT otros (#PCDATA)>
<!ELEMENT referencias (#PCDATA)>
<!ELEMENT observaciones (#PCDATA)>

=== holamellamoyago/DAM-24-25-YOM/Asignaturas/Lenguaje de marcas/Trimestre 2/Unidad 3/UD3_T8_yagootero_yagootero.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE curriculumVitae SYSTEM "UD3_T8_yagootero.dtd">
<curriculumVitae>
  <presentacion>Hola buenas esté es mi cv</presentacion>
  <estudios notaMedia="5">DAM1</estudios>
  <experienciaLaboral>
      <nombre>
          Fandicosta      
      </nombre>  
      <horas>200</horas>
  </experienciaLaboral>
  <idiomas nombre="gallego" nivel="medio"></idiomas>
  <deportes>Correr</deportes>
  <referencias>Fandicosta</referencias>
  <observaciones>Muy buen trabajador</observaciones>

</curriculumVitae>
