<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mensaxe [
	<!ELEMENT mensaxe (de,para+,asunto,corpo?,adxunto*)>
	<!ATTLIST mensaxe prioridad (baja | normal | urgente) #REQUIRED>
	<!ELEMENT de (#PCDATA)>
	<!ELEMENT para (#PCDATA)>
	<!ELEMENT asunto (#PCDATA)>
	<!ELEMENT corpo (#PCDATA)>
	<!ELEMENT adxunto (#PCDATA)>
]>
<mensaxe prioridad="baja">
	<de>yagootero2003@gmail.com</de>
	<para>Paco@pacos.com</para>
	<asunto>Compra de patatas</asunto>
	<corpo>Comprar patacas, 2 kg</corpo>
</mensaxe>