=== holamellamoyago/DAM-24-25-YOM/Asignaturas/Lenguaje de marcas/Trimestre 2/Unidad 4/Examenes/EXA6.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    <xs:element name="biblioteca">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="sala" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        
        <!-- Te puse las claves como key porquÃ© no me quedaba clar si las
            querias ocmo unique o key -->
        <xs:key name="PK_LIBRO">
            <xs:selector xpath="sala/libro"/>
            <xs:field xpath="@codigo"/>
        </xs:key>
        
        <xs:key name="PK_sala">
            <xs:selector xpath="sala"/>
            <xs:field xpath="@id"/>
        </xs:key>
    </xs:element>
    
    <xs:element name="sala">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="libro" maxOccurs="unbounded"/>
                <xs:element ref="empleado" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="id" type="typeID"/>
            <xs:attribute name="capacidad" type="xs:unsignedByte" use="optional"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="libro">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="titulo" type="xs:string"/>
                <xs:element name="autor">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element name="fecha" type="xs:gYear" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="codigo" type="typeCodigoLibro"/>
            <xs:attribute name="radiacion" type="typeRadiacion" use="optional"/>
            <xs:attribute name="estado" type="typeEstado"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="empleado">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="nss" type="typeNSS"/>
                    <xs:attribute name="rol" type="typeRol"/>
                </xs:extension> 
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    
    <!-- Tipo simples --> 
    <xs:simpleType name="typeID">
        <xs:restriction base="xs:string">
            
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="typeCodigoLibro">
        <xs:restriction base="xs:string">
            <xs:pattern value="LIB-[A-Z]{3}-[0-9]{2}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="typeEstado">
        <xs:restriction base="xs:string">
            <xs:enumeration value="activo"/>
            <xs:enumeration value="retirado"/>
            <!-- Arriba al lado del type no me dejo ponerle el 
                        fixed="activo", porque? -->
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="typeNSS">
        <xs:restriction base="xs:unsignedLong">
            
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="typeRol">
        <xs:restriction base="xs:string" >
            <xs:enumeration value="bibliotecario"/>
            <xs:enumeration value="tecnico"/>
            <xs:enumeration value="seguridad"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="typeRadiacion">
        <xs:union>
            <xs:simpleType>
                <xs:restriction base="xs:string"/>
            </xs:simpleType>
            <xs:simpleType>
                <xs:restriction base="xs:decimal">
                    
                </xs:restriction>
            </xs:simpleType>
        </xs:union>
    </xs:simpleType>

</xs:schema>

=== holamellamoyago/DAM-24-25-YOM/Asignaturas/Lenguaje de marcas/Trimestre 2/Unidad 4/Examenes/EXA6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template

<!DOCTYPE biblioteca [
<!ELEMENT biblioteca (sala+)>
<!ELEMENT sala (libro+, empleado+)>
<!ELEMENT libro (titulo, autor)>
<!ELEMENT empleado (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>

<!ATTLIST libro
  codigo      CDATA  #REQUIRED
  radiacion   CDATA  #IMPLIED
  estado      (activo|retirado) "activo"
>

<!ATTLIST sala
  id          CDATA  #REQUIRED
  capacidad   CDATA  #IMPLIED
>

<!ATTLIST empleado
  nss         CDATA  #REQUIRED
  rol         (bibliotecario|tecnico|seguridad) "bibliotecario"
>
]> -->
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="EXA6.xsd">
  <sala id="S1" capacidad="50">
    <libro codigo="LIB-ABC-01" radiacion="3.2" estado="activo">
      <titulo>El Resplandor</titulo>
      <autor>Stephen <fecha>1947</fecha> King</autor>
    </libro>
    <libro codigo="LIB-DEF-02" radiacion="15.5" estado="retirado">
      <titulo>Chernobyl: Historia de un Desastre</titulo>
      <autor>Serhii Plokhy</autor>
    </libro>
    <empleado nss="112233445566" rol="bibliotecario">Ana López</empleado>
  </sala>
  
  <sala id="S2">
    <libro codigo="LIB-GHI-03" radiacion="RAD-ALPHA" estado="activo">
      <titulo>Guía de Supervivencia Nuclear</titulo>
      <autor>John Doe</autor>
    </libro>
    <empleado nss="778899001122" rol="seguridad">Carlos Méndez</empleado>
  </sala>
  
</biblioteca>
