=== holamellamoyago/DAM-24-25-YOM/Asignaturas/Lenguaje de marcas/Trimestre 2/Unidad 4/Examenes/EXA7.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
           <xs:include schemaLocation="EXA7_TYPES.xsd"/>
           <xs:include schemaLocation="EXA7_ATTGROUPS.xsd"/>
           
    <xs:element name="central_nuclear">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="reactor" maxOccurs="unbounded"/>
                <xs:element ref="empleado" maxOccurs="unbounded"/>
                <xs:element ref="registro_incidentes" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
        
        <xs:key name="PK_REACTOR">
            <xs:selector xpath="reactor"></xs:selector>
            <xs:field xpath="@id"/>
        </xs:key>
        
        <xs:key name="PK_COMBUSTIBLE">
            <xs:selector xpath="reactor/combustible"/>
            <xs:field xpath="@codigo"/>
        </xs:key>
    </xs:element>
    
    <xs:element name="reactor">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="combustible" maxOccurs="3"/>
                <xs:element name="temperatura" type="typeTemperatura"/>
            </xs:sequence>
            <xs:attributeGroup ref="groupReactor"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="combustible">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tipo" type="xs:string"/>
                <xs:element name="nivel_radiacion" type="xs:unsignedByte"/>
            </xs:sequence>
            <xs:attributeGroup ref="groupCombustible"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="empleado">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="nss" type="typeNSS"/>
                    <xs:attribute name="acceso" type="typeAcceso"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="registro_incidentes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="incidente" maxOccurs="unbounded">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element name="ubicacion" type="xs:string"/>
                        </xs:sequence>
                            <xs:attribute name="fecha" type="xs:date"/>
                            <xs:attribute name="codigo_error" type="typeError"/>
                            <xs:attribute name="descripcion" type="typeDescripcion" use="optional"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== holamellamoyago/DAM-24-25-YOM/Asignaturas/Lenguaje de marcas/Trimestre 2/Unidad 4/Examenes/EXA7.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template

<!DOCTYPE central_nuclear [
<!ELEMENT central_nuclear (reactor+, empleado+, registro_incidentes?)>
<!ELEMENT reactor (combustible+, temperatura)>
<!ELEMENT combustible (tipo, nivel_radiacion)>
<!ELEMENT empleado (#PCDATA)>
<!ELEMENT registro_incidentes (incidente+)>

<!ATTLIST reactor
  id              CDATA  #REQUIRED
  estado          (activo|mantenimiento|apagado) "activo"
  ultima_revision CDATA  #IMPLIED
>

<!ATTLIST combustible
  codigo          CDATA  #REQUIRED
  peligrosidad    (baja|media|alta) "media"
>

<!ATTLIST empleado
  nss             CDATA  #REQUIRED
  acceso          (basico|avanzado|admin) "basico"
>

<!ATTLIST incidente
  fecha           CDATA  #REQUIRED
  codigo_error    CDATA  #REQUIRED
  descripcion     CDATA  #IMPLIED
>
]>-->
<central_nuclear xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:noNamespaceSchemaLocation="EXA7.xsd">
  <reactor id="R1" estado="activo" ultima_revision="2025-01-15">
    <combustible codigo="COMB-A12-34" peligrosidad="alta">
      <tipo>Uranio-235</tipo>
      <nivel_radiacion>150</nivel_radiacion>
    </combustible>
    <temperatura>40.0</temperatura>
  </reactor>
  <empleado nss="900001234567" acceso="admin">Ana LÃ³pez</empleado>
  <registro_incidentes>
    <incidente fecha="2025-03-10" codigo_error="ERR-TM-001-CRITICO">
      Fuga en <ubicacion>Sector B</ubicacion>
    </incidente>
  </registro_incidentes>
</central_nuclear>
