=== holamellamoyago/DAM-24-25-YOM/Asignaturas/Lenguaje de marcas/Trimestre 2/Unidad 4/Tarea 4/UD4_T4C_yagootero.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="panaderias">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="panaderia" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="panaderia">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="idPanaderÃ­a" type="xs:integer"/>
                <xs:element name="domicilio" type="xs:string" minOccurs="0"/>
                <xs:element name="telefono" type="xs:integer"/>
                <xs:element ref="pedido"/>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="codPedido">
            <xs:selector xpath="pedido"/>
            <xs:field xpath="@numPedido"/>
        </xs:key>
    </xs:element>
    
    <xs:element name="pedido">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="fecha" type="xs:string"/>
                <xs:element name="ingrediente" maxOccurs="15">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="idIngrediente" type="xs:integer"/>
                            <xs:element name="ano" type="xs:integer"/>
                            <xs:element name="origen">
                                <xs:complexType>
                                    <xs:attribute name="continente" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="numPedido" type="xs:integer"/>
            <xs:attribute name="tipo" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    
    <xs:simpleType name="restAno">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1970"/>
            <xs:maxInclusive value="2050"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== holamellamoyago/DAM-24-25-YOM/Asignaturas/Lenguaje de marcas/Trimestre 2/Unidad 4/Tarea 4/UD4_T4C_yagootero.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->
<!--
<!DOCTYPE panaderias [
<!ELEMENT panaderias (panaderia*)>
<!ELEMENT panaderia (idPanadería, domicilio?,telefono+,pedido+)>
<!ELEMENT idPanadería (#PCDATA)>
<!ELEMENT domicilio (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT pedido (fecha, ingrediente+)>
<!ATTLIST pedido
  numPedido ID #REQUIRED
  tipo (urgente | normal) "normal">
 <!ELEMENT fecha (#PCDATA)> 
<!ELEMENT ingrediente (idIngrediente, ano, origen?)>
<!ELEMENT idIngrediente (#PCDATA)>
<!ELEMENT ano (#PCDATA)>
<!ELEMENT origen EMPTY>
<!ATTLIST origen
  continente (Europa | America | Africa) #REQUIRED>

]>
-->
<panaderias xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="UD4_T4C_yagootero.xsd">
   <panaderia>
    <idPanadería>1</idPanadería>
    <domicilio>Rua Ferrol</domicilio>
    <telefono>692433876</telefono>
    <pedido numPedido="1" tipo="urgente">
      <fecha>11-02-03</fecha>
      <ingrediente>
        <idIngrediente>1</idIngrediente> 
        <ano>2025</ano>
        <origen continente="Europa"/>
      </ingrediente>
    </pedido>
   </panaderia> 
</panaderias>
