=== holamellamoyago/DAM-24-25-YOM/Asignaturas/Lenguaje de marcas/Trimestre 3/Recuperación/Ejercicio2.dtd
<!ELEMENT universidad (departamento+, alumno+, asignatura+ )>



<!ELEMENT departamento (nombre, profesor, aula)>



<!ELEMENT profesor (nombre, asignaturas)>
<!ELEMENT nombre (#PCDATA)>

<!ATTLIST asignatura codigo ID #REQUIRED >
<!ELEMENT asignaturas (IDREFS) >

<!ELEMENT aula EMPTY>
<!ATTLIST departamento codigo ID #REQUIRED >
<!ATTLIST departamento tipo (ciencias, humanidades, ingenierÃ­a) #REQUIRED >
<!ATTLIST profesor id ID #REQUIRED >
<!ATTLIST profesor jefe BOOLEAN #REQUIRED >
<!ATTLIST aula numero NMTOKEN #REQUIRED >
<!ATTLIST aula capacidad CDATA #REQUIRED >
<!ATTLIST aula recursos CDATA #REQUIRED >


<!ELEMENT alumno (nombre, telefono) >
<!ELEMENT telefono (#PCDATA) >
<!ATTLIST alumno id ID #REQUIRED >
<!ATTLIST alumno matriculas IDREFS #REQUIRED >

<!ELEMENT asignatura (nombre, horario) >
<!ELEMENT horario EMPTY >


<!ATTLIST asignatura departamento IDREF #REQUIRED >
<!ATTLIST asigntatura creditos CDATA #REQUIRED >
<!ATTLIST horario dia (L, M, X, J, V) #REQUIRED >
<!ATTLIST horario hora CDATA #REQUIRED >

=== holamellamoyago/DAM-24-25-YOM/Asignaturas/Lenguaje de marcas/Trimestre 3/Recuperación/Ejercicio2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE universidad SYSTEM "Ejercicio2.dtd">
<universidad>
    <departamento codigo="D1" tipo="ciencias">
        <nombre>Matemáticas</nombre>
        <profesor id="P001" jefe="true">
            <nombre>Carlos Ruiz</nombre>
            <asignaturas>MAT101 MAT102</asignaturas>
        </profesor>
        <aula numero="A101" capacidad="50" recursos="proyector pizarra"/>
    </departamento>
    
    <alumno id="A001" matriculas="MAT101 MAT102">
        <nombre>Ana López</nombre>
        <telefono tipo="móvil">600123456</telefono>
    </alumno>
    
    <asignatura codigo="MAT101" departamento="D1" creditos="6">
        <nombre>Álgebra Lineal</nombre>
        <horario dia="L" hora="09:00"/>
    </asignatura>
</universidad>
