=== holamellamoyago/DAM-24-25-YOM/Asignaturas/Lenguaje de marcas/Trimestre 3/Recuperación/Ejercicio1_dtd.dtd
<!ELEMENT biblioteca (libro+, usuario+)>
<!ELEMENT libro (titulo, autor , año, prestado_a?)>
<!ELEMENT usuario (nombre, telefono?)>

<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT año (#PCDATA)>
<!ELEMENT prestado_a EMPTY>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>



<!ATTLIST libro id ID #REQUIRED>
<!ATTLIST libro categoria (novela | ciencia | drama | documental) #REQUIRED>

<!ATTLIST prestado_a usuario IDREFS #REQUIRED>

<!ATTLIST usuario id ID #REQUIRED>

=== holamellamoyago/DAM-24-25-YOM/Asignaturas/Lenguaje de marcas/Trimestre 3/Recuperación/Ejercicio1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "Ejercicio1_dtd.dtd">
<biblioteca>
    <libro id="L001" categoria="novela">
        <titulo>Don Quijote de la Mancha</titulo>
        <autor>Miguel de Cervantes</autor>
        <año>1605</año>
        <prestado_a usuario="U123"/>
    </libro>
    <libro id="L002" categoria="ciencia">
        <titulo>Breves respuestas a grandes preguntas</titulo>
        <autor>Stephen Hawking</autor>
        <año>2018</año>
    </libro>
    <usuario id="U123">
        <nombre>Ana García</nombre>
        <telefono>600111222</telefono>
    </usuario>
</biblioteca>
