=== holamellamoyago/DAM-24-25-YOM/Asignaturas/Lenguaje de marcas/Trimestre 2/Unidad 4/Tarea 5/UD4_T5A_yagootero.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="edificio">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="enderezo"/>
                <xs:element ref="dataConstrucion"/>
                <xs:element name="material" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="alquiler" type="xs:string"/>
            <xs:attribute name="valor" type="tipoValor"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="enderezo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="rua" type="xs:string"/>
                <xs:element name="numero" type="tipoRua"/>
                <xs:element name="poboacion" type="xs:string"/>
                <xs:element name="provincia" type="xs:string"/>
                <xs:element name="codigoPostal" type="tipoCodPostal"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:simpleType name="tipoValor">
        <xs:restriction base="xs:decimal">
            <xs:fractionDigits value="2"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="tipoRua">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="2000"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="tipoCodPostal">
        <xs:restriction base="xs:int">
            <xs:pattern value="[0-9]{5}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:element name="dataConstrucion">
        <xs:complexType>
            <xs:attribute name="mes" type="tipoMes"/>
            <xs:attribute name="ano" type="xs:int"/>
        </xs:complexType>
    </xs:element>
    
    <xs:simpleType name="tipoMes">
        <xs:restriction base="xs:string">
            <xs:enumeration value="eneiro"/>
            <xs:enumeration value="febreiro"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="tipoano">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="1950"/>
            <xs:maxInclusive value="2025"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== holamellamoyago/DAM-24-25-YOM/Asignaturas/Lenguaje de marcas/Trimestre 2/Unidad 4/Tarea 5/UD4_T5A_yagootero.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->



<edificio alquiler="verdadeiro" valor="410.50" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="UD4_T5A_yagootero.xsd">
   <enderezo>
      <rua>Ponzano</rua>
      <numero>66</numero>
      <poboacion>Madrid</poboacion>
      <provincia>Madrid</provincia>
      <codigoPostal>28003</codigoPostal>
   </enderezo>
   <dataConstrucion mes="eneiro" ano="1989" />
   <material>formig√≥n</material>
</edificio>
