=== holamellamoyago/DAM-24-25-YOM/Asignaturas/Lenguaje de marcas/Trimestre 2/Unidad 4/Tarefa 4b/UD4_T4B_tarefa_A_yagootero.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="supermercado">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="articulo" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="articulo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="descripcion" type="xs:string"/>
                <xs:element name="marca" type="xs:string" minOccurs="0"/>
                <xs:element name="medida" type="xs:string"/>
                <xs:element name="seccion" type="xs:string"/>
                <xs:element name="oferta" type="xs:string" 
                            minOccurs="0" maxOccurs="unbounded"/>
                    <xs:element name="perecedero" minOccurs="0">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="fabricacion" type="xs:string" minOccurs="0"/>
                                <xs:element name="caducidad" type="xs:string" minOccurs="0"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== holamellamoyago/DAM-24-25-YOM/Asignaturas/Lenguaje de marcas/Trimestre 2/Unidad 4/Tarefa 4b/UD4_T4B_tarefaA_yagootero.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->
<supermercado xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="UD4_T4B_tarefa_A_yagootero.xsd">
   <articulo id="articulo1">
     <descripcion>Leche desntada</descripcion>
     <marca>Pascual</marca>
     <medida>1 L</medida>
     <seccion>Leche y Batidos</seccion>
   </articulo>
   <articulo id="articulo2">
     <descripcion>Leche entera</descripcion>
     <marca>Puleva</marca>
     <medida>1,5 L</medida>
     <seccion>Leche y Batidos</seccion>
     <oferta>Lote descuento</oferta>
     <oferta>Dos por uno</oferta>
     <perecedero>
        <fabricacion>Enero2010</fabricacion>
     </perecedero>
   </articulo>
   <articulo id="articulo3">
     <descripcion>Tomate s</descripcion>
     <medida>1 Kg</medida>
     <seccion>Frutas y verduras</seccion>
     <perecedero>
        <caducidad>Febrero2010</caducidad>
     </perecedero>
   </articulo>
</supermercado>
