=== holamellamoyago/DAM-24-25-YOM/Asignaturas/Lenguaje de marcas/Trimestre 2/Unidad 4/Tarea 2B/UD4_T2B_tarefaB_yagootero.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" >
  <xs:element name="personas">
       <xs:complexType>
          <xs:sequence>
             <xs:element name="persona" maxOccurs="unbounded">
               <xs:complexType>
                 <xs:all>
                    <xs:element name="nombre" type="xs:string" />
                    <xs:element name="apellido" type="xs:string" />
                    <xs:element name="fechanacimiento" type="xs:date"/>
                    <xs:element name="numerodocumento" type="xs:int"/>
                    <xs:element name="trianero" type="xs:boolean"/>
                 </xs:all>
               </xs:complexType>
             </xs:element>
          </xs:sequence>
       </xs:complexType>
  </xs:element>
</xs:schema>

=== holamellamoyago/DAM-24-25-YOM/Asignaturas/Lenguaje de marcas/Trimestre 2/Unidad 4/Tarea 2B/UD4_T2B_tarefaB_yagootero.xml
<?xml version="1.0" encoding="UTF-8"?>
<personas  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="UD4_T2B_tarefaB_yagootero.xsd">
  <persona>
    <nombre>Pepa</nombre>  
    <apellido>Galan</apellido>
    <fechanacimiento>2024-12-31</fechanacimiento>
    <numerodocumento>123456</numerodocumento>
    <trianero>true</trianero>
  </persona>
  <persona>
    <nombre>Pepa</nombre>  
    <apellido>Galan</apellido>
    <fechanacimiento>2024-12-31</fechanacimiento>
    <numerodocumento>123456</numerodocumento>
    <trianero>true</trianero>
  </persona>
</personas>
